"""replace player birthdate with age

Revision ID: 3a5177d7e368
Revises: 7d6a9769dd2a
Create Date: 2026-07-30 20:37:42.126472

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3a5177d7e368'
down_revision: Union[str, Sequence[str], None] = '7d6a9769dd2a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('player', sa.Column('age', sa.Integer(), nullable=True))
    op.drop_column('player', 'birthdate')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('player', sa.Column('birthdate', sa.DATE(), autoincrement=False, nullable=True))
    op.drop_column('player', 'age')
    # ### end Alembic commands ###
