"""add record to team

Revision ID: 8f4afbbc94e4
Revises: 3a5177d7e368
Create Date: 2026-08-07 18:48:40.838795

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8f4afbbc94e4'
down_revision: Union[str, Sequence[str], None] = '3a5177d7e368'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('team', sa.Column('wins', sa.Integer(), nullable=True))
    op.add_column('team', sa.Column('losses', sa.Integer(), nullable=True))
    op.add_column('team', sa.Column('ties', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('team', 'ties')
    op.drop_column('team', 'losses')
    op.drop_column('team', 'wins')
    # ### end Alembic commands ###
